#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/josue/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# abnt2
setxkbmap -model abnt2 br &

# wallpaper
feh --bg-scale "/home/josue/Imagens/wallhaven-156221.jpg" &

# mount permission
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# enable audio
start-pulseaudio-x11 &
#pulseaudio --start &

# valume control
volumeicon &

nm-applet &

batterymon &

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/jonatas/.fluxbox/log"
